backend:
  name: github
  repo: Yackson-EX/yacksons-world
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "pubDate", label: "Publish date", widget: "datetime" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "reviews"
    label: "Reviews"
    folder: "src/content/reviews"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "pubDate", label: "Publish date", widget: "datetime" }
      - name: "medium"
        label: "Type"
        widget: "select"
        options: ["games", "music", "movies", "tv-shows", "anime"]
      - { name: "body", label: "Body", widget: "markdown" }
